repos:
  - repo: local
    hooks:
      - id: make-format
        name: Run make format
        entry: bash -c "make format && git add -u"
        language: system
        pass_filenames: false
        always_run: true